### ISSUE TITLE
Where can find the custom type examples?

### ISSUE THREAD

**Issue by Eipgen** [torchmd/torchmd-net#171]
Dear Developers:
          Recently I follow the the part **Creating a new dataset** to build my datasets. But i meet the error below, it's seems my data fromat or dtype is wrong. I'm not sure whether my datasets is True or not
1. So where I can find the right data format with **custom**? 
2. Can you give a examples about the datasets type, such as CH4 or benzene?

Thank you.

```markdown
Global seed set to 1
Multiprocessing is handled by SLURM.
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Global seed set to 1
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:611: UserWarning: Checkpoint directory /scratch/job.2656/output exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]

  | Name  | Type        | Params
--------------------------------------
0 | model | TorchMD_Net | 6.9 M
--------------------------------------
6.9 M     Trainable params
0         Non-trainable params
6.9 M     Total params
27.460    Total estimated model params size (MB)
/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/loggers/csv_logs.py:57: UserWarning: Experiment logs directory output/ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
SLURM auto-requeueing enabled. Setting signal handlers.
Traceback (most recent call last):
  File "/home/jxiao/mambaforge/envs/torchmd-net/bin/torchmd-train", line 33, in <module>
    sys.exit(load_entry_point('torchmd-net', 'console_scripts', 'torchmd-train')())
  File "/home/jxiao/soft/torchmd-net/torchmdnet/scripts/train.py", line 167, in main
    trainer.fit(model, data)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 154, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 347, in validation_step
    return self.model(*args, **kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    return self.module.validation_step(*inputs, **kwargs)
  File "/home/jxiao/soft/torchmd-net/torchmdnet/module.py", line 64, in validation_step
    return self.step(batch, mse_loss, "val")
  File "/home/jxiao/soft/torchmd-net/torchmdnet/module.py", line 79, in step
    y, neg_dy = self(
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jxiao/soft/torchmd-net/torchmdnet/module.py", line 56, in forward
    return self.model(z, pos, batch=batch, q=q, s=s, extra_args=extra_args)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jxiao/soft/torchmd-net/torchmdnet/models/model.py", line 210, in forward
    x, v, z, pos, batch = self.representation_model(z, pos, batch, q=q, s=s)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jxiao/soft/torchmd-net/torchmdnet/models/torchmd_et.py", line 161, in forward
    edge_index, edge_weight, edge_vec = self.distance(pos, batch)
  File "/home/jxiao/mambaforge/envs/torchmd-net/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jxiao/soft/torchmd-net/torchmdnet/models/utils.py", line 237, in forward
    edge_weight[mask] = torch.norm(edge_vec[mask], dim=-1)
RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Double for the source.
~
 ```
The input yaml file
```yaml
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 32
charge: false
coord_files: data3/p*.npy
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: Custom
dataset_arg: null
dataset_root: ./data3
derivative: false
distance_influence: both
early_stopping_patience: 150
ema_alpha_neg_dy: 1.0
ema_alpha_y: 1.0
embed_files: data3/z*.npy
embedding_dimension: 256
energy_files: data3/e*.npy
force_files: data3/f*.npy
inference_batch_size: 128
load_model: null
log_dir: output/
lr: 0.0004
lr_factor: 0.8
lr_metric: val_loss
lr_min: 1.0e-07
lr_patience: 15
lr_warmup_steps: 10000
max_num_neighbors: 64
max_z: 100
model: equivariant-transformer
neg_dy_weight: 1.0
neighbor_embedding: true
ngpus: -1
num_epochs: 3000
num_heads: 8
num_layers: 8
num_nodes: 1
num_rbf: 64
num_workers: 6
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
reset_trainer: false
save_interval: 10
seed: 1
spin: false
splits: null
standardize: false
tensorboard_use: false
test_interval: 10
test_size: null
train_size: 76
trainable_rbf: false
val_size: 24
wandb_name: training
wandb_project: training_
wandb_use: false
weight_decay: 0.0
y_weight: 1.0

**Comment by RaulPPelaez** [comment]
This morning this PR of mine #170 was merged, it aimed to fix this exact issue.
Could you confirm that you are using the latest master currently?
In which case, it seems that my fix is actually causing problems.

**Comment by Eipgen** [comment]
I fix the code with specfic tensor dtype, and now I can train smoothly, but i still pay attention to this fix.
https://github.com/torchmd/torchmd-net/blob/664a4d234a10c680580733aed67b7f6fcbff8dc8/torchmdnet/datasets/custom.py#L87
```
pos=torch.from_numpy(coord_data).float(), z=torch.from_numpy(embed_data).long()
```

**Comment by RaulPPelaez** [comment]
Interesting, so custom is always loading data as double, which causes everything to turn double down the line.
I am not sure what we want to do about this. Custom returning double precision seems sensible to me, since the user can afterwards convert to float if necessary, whereas the opposite cast results in loss of accuracy.

Maybe @stefdoerr @PhilippThoelke can give us some guidance here on how to procede.

In the meantime I assume your original issue is fixed by using the latest commit from master.

**Comment by giadefa** [comment]
I have not followed much but data can be double but the models are all
single, so at some point we need to convert.

**Comment by julien-blanchon** [comment]
What did the `energyglob` expect as input ? I'm trying to give him a a molecule-wise energy but, it crash at `energy_data.shape[0]` (l68) as a atom-wise may be expected

**Comment by julien-blanchon** [comment]
> I believe you should have these shapes:
> 
> ```
> coord.shape = (n_mol, n_atoms, 3)
> energy.shape = (n_mol, 1)
> ```

Sorry I forget to close this.

Yes this correct
