### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by xiehuanyi** [torchmd/torchmd-net#211]
I have some trouble runing the example script. So, I directly use pytorch_lightning to train on my data. and my code are like this
```
from torchmdnet.models.model import load_model
import numpy as np
from torch.utils.data import Dataset, DataLoader
import random
import torch
import yaml
from torch import nn
from torchmdnet.models.torchmd_et import TorchMD_ET
import pytorch_lightning as pl


class LightningModel(pl.LightningModule):
    def __init__(self):
        super(LightningModel, self).__init__()
        self.model = load_model("ckpts/et-md17/epoch=2139-val_loss=0.2543-test_loss=0.2317.ckpt", 
                                derivative=True, max_num_neighbors=64)
        self.loss_fn = torch.nn.MSELoss()
    
    def forward(self, z, pos, batch_ind):
        return self.model(z, pos, batch_ind)
    
    def training_step(self, batch, batch_idx):
        z, pos, energy, forces, batch_ind = batch
        pos.requires_grad = True
        pred_ene, pred_for = self(z, pos, batch_ind)
        loss_ene = self.loss_fn(pred_ene, energy)
        loss_for = self.loss_fn(pred_for, forces)
        print(f'pred_for {pred_for.requires_grad}, pos {pos.requires_grad}')
        loss = loss_ene + 100 * loss_for
        if batch_idx == 100:
            print('train loss', loss, 'loss energy', loss_ene, 'loss forces', loss_for)
        self.log('train loss', loss, 'loss energy', loss_ene, 'loss forces', loss_for)
        return loss
    
    def validation_step(self, batch, batch_idx):
        z, pos, energy, forces, batch_ind = batch
        pred_ene, pred_for = self(z, pos, batch_ind)
        loss_ene = nn.functional.mse_loss(pred_ene, energy)
        loss_for = nn.functional.mse_loss(pred_for, forces)
        val_loss = (loss_ene + 100 * loss_for)
        self.log('val_loss', val_loss, 'val_energy_loss', loss_ene, 'val_forces_loss', loss_for)
        
    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=1e-4)
    

class Molset(Dataset):
    def __init__(self, data, train_radio=0.9, mode='train'):
        super().__init__()
        self.mode = mode
        self.train_radio = train_radio
        self.data = data
        
        length = len(self.data)
        indices = np.random.permutation(length)
        train_size = int(length * self.train_radio)
        
        if self.mode == 'train':
            self.data = self.data[indices[:train_size]]
        else:
            self.data = self.data[indices[train_size:]]
    
    def __getitem__(self, idx):
        data = self.data[idx]
        z, pos, energy, forces = data['elements'], data['coordinates'], data['energy'], data['force']
        z = np.array(z)
        energy = np.array([energy])
        forces = forces.reshape([-1, 3])
        return z, pos, energy, forces
    
    def __len__(self):
        return len(self.data)

def collate_fn(batch):
    zs = [i[0] for i in batch]
    poses = [i[1] for i in batch]
    energy = [i[2] for i in batch]
    forces = [i[3] for i in batch]
    batch_ind = []
    for idx, sample in enumerate(batch):
        batch_ind += [idx] * len(sample[0])
    
    zs = np.concatenate(zs, axis=0)
    poses = np.concatenate(poses, axis=0)
    energy = np.concatenate(energy, axis=0)
    forces = np.concatenate(forces, axis=0)
    batch_ind = np.array(batch_ind)
    return torch.tensor(zs, dtype=torch.long), \
            torch.tensor(poses, dtype=torch.float32), \
            torch.tensor(energy, dtype=torch.float32), \
            torch.tensor(forces, dtype=torch.float32), \
            torch.tensor(batch_ind, dtype=torch.long)

data = np.load('d.npy', allow_pickle=True)
train_loader = DataLoader(Molset(data), batch_size=16, collate_fn=collate_fn, num_workers=8)
eval_loader = DataLoader(Molset(data, mode='eval'), batch_size=16, collate_fn=collate_fn, num_workers=8)

model = LightningModel()
trainer = pl.Trainer(max_epochs=2, log_every_n_steps=100)
trainer.fit(model, train_loader, eval_loader)
```
However, it gave a error
```
root@f932e8a003804011ee08fce0c73e6100b9fd-task1-0:/code# python eqv1.py 
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:67: UserWarning: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
  warning_cache.warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name    | Type        | Params
----------------------------------------
0 | model   | TorchMD_Net | 1.3 M 
1 | loss_fn | MSELoss     | 0     
----------------------------------------
1.3 M     Trainable params
0         Non-trainable params
1.3 M     Total params
5.160     Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                      | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "eqv1.py", line 100, in <module>
    trainer.fit(model, train_loader, eval_loader)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1014, in _run_stage
    self._run_sanity_check()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1043, in _run_sanity_check
    val_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 375, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 291, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 379, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "eqv1.py", line 37, in validation_step
    pred_ene, pred_for = self(z, pos, batch_ind)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "eqv1.py", line 20, in forward
    return self.model(z, pos, batch_ind)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/code/torchmd-net/torchmdnet/models/model.py", line 289, in forward
    dy = grad(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
Any ideas to fix it?

**Comment by RaulPPelaez** [comment]
Show us your env: $mamba list

Depending on the lightning version you are using, you might need to pass "inference_mode=True" to Trainer, since TorchMD-Net models require to run backwards as part of forwards to compute forces from energies.

**Comment by RaulPPelaez** [comment]
I am closing this as stale, please feel free to reopen if the issue persist.
